# ThreadManor configuration
# ThreadManor configuration
# Set the maximum number of worker threads requested
max.workers=25
# (Optional) Indicate how many the system is capable of running
# If present, ThreadManor will use the smaller of max.workers and capable.workers
# Example: capable.workers=4
# If not present, Java's Runtime.availableProcessors() will be used
#capable.workers=4
